/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author hp 14
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtSueldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtHijos = new javax.swing.JTextField();
        cmdConsultar = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        TxtBonificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel1.setText("Bonificación En Su Sueldo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese Sueldo ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        TxtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSueldoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Cuantos Hijos tiene ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        TxtHijos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtHijosKeyTyped(evt);
            }
        });
        jPanel1.add(TxtHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 30, -1));

        cmdConsultar.setBackground(new java.awt.Color(0, 0, 0));
        cmdConsultar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmdConsultar.setForeground(new java.awt.Color(255, 255, 255));
        cmdConsultar.setText("Consultar Bonificación");
        cmdConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Usted Tiene Un Monto De Bonificación De:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        TxtBonificacion.setEditable(false);
        TxtBonificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBonificacionKeyTyped(evt);
            }
        });
        jPanel1.add(TxtBonificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 130, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Su Monto Total Es:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, -1));

        TxtMonto.setEditable(false);
        TxtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMontoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConsultarActionPerformed
        String monto,montob;
        int sueldo,hijos;
        
        if (TxtSueldo.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite  Su Sueldo","error", JOptionPane.ERROR_MESSAGE);
         TxtSueldo.requestFocusInWindow();
     }else if(TxtHijos.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite El Numero De Hijos ","error", JOptionPane.ERROR_MESSAGE);
         TxtHijos.requestFocusInWindow();
     }
     else {
        
        
        sueldo=Integer.parseInt(TxtSueldo.getText());
        hijos=Integer.parseInt(TxtHijos.getText());
        int bonificacion= 80000*hijos;
        int salarioT=sueldo+bonificacion;    
      
     montob=String.valueOf(bonificacion);
     TxtBonificacion.setText(montob);
     
     monto=String.valueOf(salarioT);
     TxtMonto.setText(monto);
     }
    }//GEN-LAST:event_cmdConsultarActionPerformed

    private void TxtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMontoKeyTyped

    }//GEN-LAST:event_TxtMontoKeyTyped

    private void TxtBonificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBonificacionKeyTyped

    }//GEN-LAST:event_TxtBonificacionKeyTyped

    private void TxtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSueldoKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume();}
    }//GEN-LAST:event_TxtSueldoKeyTyped

    private void TxtHijosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtHijosKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume();}
    }//GEN-LAST:event_TxtHijosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtBonificacion;
    private javax.swing.JTextField TxtHijos;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JTextField TxtSueldo;
    private javax.swing.JToggleButton cmdConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
